###
GET http://{{IP}}:8088/openapi/v1/algo/ins/list HTTP/1.1

### DELETE
POST http://{{IP}}:8088/openapi/v1/algo/ins/delete HTTP/1.1
content-type: application/json

{
    "algo_id": "f47e6ef5a3835880a187639b792495228bcb48c8",
    "stream_id": "stream_1718426183_11"
}

### UPDATE
POST http://{{IP}}:8088/openapi/v1/algo/ins/create_or_update HTTP/1.1
content-type: application/json

{
    "camera_id": "1718426183",
    "algo_id": "f47e6ef5a3835880a187639b792495228bcb48c8",
    "screenshot": {
        "strategy": "KEY",
        "step": 2
    },
    "custom_info": {
        "custom_pair": [
            {
                "key": "name",
                "value": "wings11123",
                "value_type": "STRING"
            }
        ]
    }
}

